insert into Room (R_id, type, price) values (1, 'myHELPER', 210);
insert into Room (R_id, type, price) values (2, 'Klor-Con', 440);
insert into Room (R_id, type, price) values (3, 'Sodium Bicarbonate', 177);
insert into Room (R_id, type, price) values (4, 'SPRYCEL', 489);
insert into Room (R_id, type, price) values (5, 'Amazonian Colored Clay Foundation Broad Spectrum SPF 15 Sunscreen', 366);
insert into Room (R_id, type, price) values (6, 'Elestrin', 156);
insert into Room (R_id, type, price) values (7, 'LOVASTATIN', 227);
insert into Room (R_id, type, price) values (8, 'CLARINSMEN Antiperspirant ALL DAY DRY ALCOHOL-FREE', 143);
insert into Room (R_id, type, price) values (9, 'Folic Acid', 272);
insert into Room (R_id, type, price) values (10, 'Epinephrine', 555);
insert into Room (R_id, type, price) values (11, 'Ibuprofen', 577);
insert into Room (R_id, type, price) values (12, 'Tranylcypromine Sulfate', 142);
insert into Room (R_id, type, price) values (13, 'Ibuprofen', 194);
insert into Room (R_id, type, price) values (14, 'Doxazosin Mesylate', 329);
insert into Room (R_id, type, price) values (15, 'Retin-A MICRO', 93);
insert into Room (R_id, type, price) values (16, 'PRAMIPEXOLE DIHYDROCHLORIDE', 418);
insert into Room (R_id, type, price) values (17, 'Fair Foundation SPF 15', 542);
insert into Room (R_id, type, price) values (18, 'ADRUCIL', 405);
insert into Room (R_id, type, price) values (19, 'harmon face values night time relief', 68);
insert into Room (R_id, type, price) values (20, 'Ibuprofen', 566);
insert into Room (R_id, type, price) values (21, 'Hydroxocobalamin', 334);
insert into Room (R_id, type, price) values (22, 'Bicalutamide', 191);
insert into Room (R_id, type, price) values (23, 'PureLife APF', 571);
insert into Room (R_id, type, price) values (24, 'Caffeine Withdrawal', 140);
insert into Room (R_id, type, price) values (25, 'UltrasolSunscreen', 189);
insert into Room (R_id, type, price) values (26, 'Veletri', 474);
insert into Room (R_id, type, price) values (27, 'citroma', 489);
insert into Room (R_id, type, price) values (28, 'Sweet Golden Pear Antibacterial Foaming Hand Wash', 394);
insert into Room (R_id, type, price) values (29, 'ck one 3-in-1 face makeup', 148);
insert into Room (R_id, type, price) values (30, 'Levothyroxine Sodium', 595);
