insert into Test (T_id, T_name, T_description, price, T_date) values (1, 'Guaifenesin', 'Lead-induced chronic gout, unspecified elbow, without tophus', 91.84, '10/4/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (2, 'Avobenzone, Octisalate, Oxybenzone and Octocrylene', 'Poisoning by oth systemic antibiotics, self-harm, sequela', 947.13, '10/3/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (3, 'Cefdinir', 'Unspecified open wound of unspecified upper arm', 394.86, '12/8/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (4, 'Ibuprofen', 'Contusion of unspecified lower leg', 247.95, '11/13/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (5, 'phenytoin sodium', 'Leakage of other urinary catheter, sequela', 945.53, '10/5/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (6, 'Diphenhydramine HCl', 'Disp fx of lateral condyle of unsp femr, 7thP', 220.09, '11/23/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (7, 'Prednisone', 'Polyp of corpus uteri', 397.58, '9/14/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (8, 'GLYCERIN', 'Poisoning by oth agents aff GI sys, self-harm, init', 497.89, '5/29/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (9, 'Bacitracin Dimethicone Zinc Oxide', 'Abnormal innervation syndrome right eye, unspecified eyelid', 305.38, '12/29/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (10, 'CAMPHOR (SYNTHETIC), MENTHOL, METHYL SALICYLATE', 'Inj muscle and tendon of unsp wall of thorax, init encntr', 179.68, '7/23/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (11, 'Titanium dioxide', 'Charcot''s joint, right elbow', 718.43, '1/30/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (12, 'TITANIUM DIOXIDE and OCTINOXATE', 'Unsp inj blood vessels at lower leg level, unsp leg, sequela', 401.32, '6/6/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (13, 'STANNOUS FLUORIDE', 'Transitory neonatal hypoparathyroidism', 941.94, '1/2/2023');
insert into Test (T_id, T_name, T_description, price, T_date) values (14, 'Oxygen', 'Acquired absence of knee', 924.87, '12/11/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (15, 'Diphenhydramine Hydrochloride', 'Displ transverse fx shaft of r fibula, 7thD', 24.58, '10/31/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (16, 'naproxen sodium', 'Foreign body in other parts of genitourinary tract, sequela', 942.76, '6/16/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (17, 'Aurum Prunus', 'Nondisp fx of shaft of second MC bone, left hand, sequela', 948.98, '7/14/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (18, 'Rizatriptan Benzoate', 'Toxic effect of contact w oth jellyfish, self-harm', 977.63, '4/24/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (19, 'Pioglitazone', 'Adverse effect of penicillins, initial encounter', 196.84, '3/5/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (20, 'Avobenzone, Homosalate, Octocrylene, and Oxybenzone', 'Sprain of ligaments of thoracic spine', 383.07, '4/28/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (21, 'Octinoxate and Oxybenzone', 'Superficial foreign body, left lesser toe(s), sequela', 467.08, '7/25/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (22, 'tretinoin', 'Diffuse TBI w loss of consciousness of 1-5 hrs 59 min, subs', 960.5, '1/22/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (23, 'fexofenadine hydrochloride', 'Unsp fx low end r tibia, subs for opn fx type I/2 w malunion', 822.22, '5/8/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (24, 'Lambs Quarters', 'Displ Maisonneuve''s fx unsp leg, 7thD', 793.94, '9/10/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (25, 'Chlordiazepoxide Hydrochloride and Clidinium Bromide', 'Other fracture of third metacarpal bone, left hand, sequela', 91.92, '1/6/2023');
insert into Test (T_id, T_name, T_description, price, T_date) values (26, 'Ropinirole Hydrochloride', 'Primary generalized (osteo)arthritis', 97.55, '4/28/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (27, 'TRICLOSAN', 'Monoplg low lmb fol oth cerebvasc disease aff unsp side', 183.55, '9/28/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (28, 'PETROLATUM', 'Advrs effect of antimalari/drugs acting on bld protzoa, sqla', 334.17, '7/7/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (29, 'methocarbamol', 'Breakdown of implanted testicular prosthesis, sequela', 41.5, '4/25/2022');
insert into Test (T_id, T_name, T_description, price, T_date) values (30, 'Diphenhydramine HCl, Phenylephrine HCl', 'Oth injury of anterior tibial artery, right leg, init encntr', 850.04, '6/22/2022');
